default:
  tags:
    - ib-bdx
    - staging
    - docker

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - test_ssh

Test cmd over ssh:
  stage: test_ssh
  tags:
    - ib-bdx
    - staging
    - shell
  script:
    - ssh vagrant@192.168.99.20 'echo $HOSTNAME'
