#############################################################
###### VARIABLES & MISE EN OEUVRE DOCKER IN DOCKER ##########
#############################################################
default:
  tags:
    - ib-bdx
    - staging
    - docker

variables:
  REGISTRY: registry.gitlab.com/rmaziere
  REPOSITORY: fil-rouge-devops
  CONTAINER_NAME: webtweet
  #IMAGE_TAG: latest
  CONTAINER_IP: 172.17.0.3
  EXTERN_PORT: 8080
  SNYK_TOKEN: "95633847-26f4-46d5-8be0-235d04d90fce"

  IMAGE_TAG: main

  STAGING_IP: 192.168.99.10
  PREPROD_IP: 192.168.99.20
  PROD_IP: 192.168.99.30
  SSH_USER: vagrant

image: docker:latest
services:
  - name: docker:dind
    alias: docker


#############################################################
######     DIFFERENTES ETAPES DE LA CI-CD   #################
#############################################################
stages:
  - Build
  - Test acceptance
  - Release image
  - Scan Securite
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging
  - Deploy pre-prod
  - Test pre-prod
  - Deploy prod
  - Test prod


#############################################################
######       FONCTION TEST DE TEMPLATE    ###################
#############################################################
.test_template: &test
  image: $REGISTRY/$REPOSITORY:${IMAGE_TAG}
  only:
    - main
  script:
    - apk --no-cache add curl
    - curl "http://$DOMAIN" | grep "Linux Tweet App!"

.test_local: &test_local
  tags:
    - ib-bdx
    - staging
    - shell
  script:
    - curl -o /dev/null --silent --head --write-out '%{http_code}\n' "http://$IP:$PORT" | grep "200" # Si code 200 => succès



#############################################################
######           BUILD         #####################
#############################################################
Phase Docker build:
  stage: Build
  script:
    - docker build -t webtweet:v1.0.0 -t webtweet:latest .
    - docker save webtweet:latest > webtweet.tar
  artifacts:
    paths:
      - webtweet.tar


#############################################################
######      TEST ET ACCEPTATION     ################
#############################################################
Phase Test acceptance:
  stage: Test acceptance
  script:
    - docker load < webtweet.tar
    - docker container stop webtweet || true
    - docker run --rm -d -p 80:80 -e PORT=80 --name webtweet webtweet:latest
    - sleep 5
    - apk --no-cache add curl
    #- curl "http://docker" | grep "Linux Tweet App!"
    - docker stop webtweet


#############################################################
######    RELEASE DE L'IMAGE SUR LE REGISTRY ##########
#############################################################
Phase Release image:
  stage: Release image
  script:
    - docker load < webtweet.tar
    - docker tag webtweet:latest "$REGISTRY/$REPOSITORY:${CI_COMMIT_REF_NAME}"
#    - docker tag webtweet "$REGISTRY/$REPOSITORY:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "$REGISTRY/$REPOSITORY:${CI_COMMIT_REF_NAME}"
#    - docker push "$REGISTRY/$REPOSITORY:${CI_COMMIT_SHORT_SHA}"


#############################################################
######    SCAN DE SECURITE - SNYK ###############
#############################################################
Phase Scan securite:
  stage: Scan Securite
  script:
    - docker run --rm -e SNYK_TOKEN=$SNYK_TOKEN
        -v /var/run/docker.sock:/var/run/docker.sock
        -v $(pwd):/app snyk/snyk:docker
        snyk test --docker $REGISTRY/$REPOSITORY:$IMAGE_TAG --json || true;


#############################################################
######   REVUE DEPLOIEMENT AVEC STOP REVIEW  ##########
#############################################################
Phase deploy review:
  stage: Deploy review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://ibdevops4amn-$CI_COMMIT_REF_NAME.herokuapp.com
    on_stop: Phase Stop review # see de label Phase Stop review BELOW
  only:
    - merge_requests
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create ibdevops4amn-$CI_COMMIT_REF_NAME || echo "project already exist"
    - heroku container:push --app ibdevops4amn-$CI_COMMIT_REF_NAME web
    - heroku container:release --app ibdevops4amn-$CI_COMMIT_REF_NAME web


#############################################################
######  STOP DE REVUE AVANT CONTINUATION ###########
#############################################################
Phase Stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy --app ibdevops4amn-$CI_COMMIT_REF_NAME -c ibdevops4amn-$CI_COMMIT_REF_NAME


#############################################################
######  DEPLOIEMENT SUR STAGING #########
#############################################################
Phase Deploy staging:
  stage: Deploy staging
  tags:
    - ib-bdx
    - staging
    - docker
  script:
    - docker container stop webtweet || true
    - docker run --rm -d -p 8080:80 --name webtweet registry.gitlab.com/rmaziere/fil-rouge-devops:main


#############################################################
###### DEPLOIEMENT SUR PREPROD #########
#############################################################
Phase Deploy pre-prod:
  stage: Deploy pre-prod
  tags:
    - ib-bdx
    - staging
    - shell
  script:
    - ssh $SSH_USER@$PREPROD_IP 'echo Welcome on $HOSTNAME'
    - ssh $SSH_USER@$PREPROD_IP 'docker container stop webtweet || true'
    - ssh $SSH_USER@$PREPROD_IP 'docker run --rm -d -p 8080:80 --name webtweet registry.gitlab.com/rmaziere/fil-rouge-devops:main'


#############################################################
###### DEPLOIEMENT SUR PROD    #########
#############################################################
Phase Deploy prod:
  stage: Deploy prod
  tags:
    - ib-bdx
    - staging
    - shell
  script:
    - ssh $SSH_USER@$PROD_IP 'echo Welcome on $HOSTNAME'
    - ssh $SSH_USER@$PROD_IP 'docker container stop webtweet || true'
    - ssh $SSH_USER@$PROD_IP 'docker run --rm -d -p 8080:80 --name webtweet registry.gitlab.com/rmaziere/fil-rouge-devops:main'


#############################################################
######  3 PHASES TESTS POUR STAING PREPROD ET PROD ##########
#############################################################

Phase de Test staging:
  <<: *test_local
  stage: Test staging
  variables:
    IP: $STAGING_IP
    PORT: $EXTERN_PORT

Phase de Test pre-prod:
  <<: *test_local
  stage: Test pre-prod
  variables:
    IP: $PREPROD_IP
    PORT: $EXTERN_PORT

Phase de Test prod:
  <<: *test_local
  stage: Test prod
  variables:
    IP: $PROD_IP
    PORT: $EXTERN_PORT
