###### MISE EN OEUVRE DOCKER IN DOCKER ###############
image: docker:latest
services:
  - name: docker:dind
    alias: docker


######           FONCTION TEST DE TEMPLATE   ###############
.test_template: &test
  image: webtweet
  only:
    - main
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep "Linux Tweet App!"  



######     DIFFERENTES ETAPES DE LA CI-CD   ###############
stages:
  - Build
  - Test acceptance


  ######           PHASE DE BUILD         ######################
docker-build:
  # Use the official docker image.
  stage: Build
  script:
    - docker build -t  webtweet:v1.0.0  ./app/
    - docker save webtweet:v1.0.0  > webtweet.tar
  artifacts:
    paths:
      - webtweet.tar    


######           PHASE DE TEST ET ACCEPTATION #############
Test acceptance:
  # Official docker image.
  stage: Test acceptance
  script:
    - docker load < webtweet.tar
    - docker run -d -p 80:8008 -e PORT=8008 --name webtweet_test webtweet
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep  "Linux Tweet App!"

