#############################################################
###### VARIABLES & MISE EN OEUVRE DOCKER IN DOCKER ##########
#############################################################
variables:
    IMAGE_NAME: registry.gitlab.com/ib35/webtweet


image: docker:latest
services:
  - name: docker:dind
    alias: docker

#############################################################
######       FONCTION TEST DE TEMPLATE    ###################
#############################################################
.test_template: &test
  image: webtweet
  only:
    - main
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep "Linux Tweet App!"  


#############################################################
######     DIFFERENTES ETAPES DE LA CI-CD   #################
#############################################################
stages:
  - Build
  - Test acceptance
  - Release image


#############################################################
######           PHASE DE BUILD         #####################
#############################################################
Phase Docker build:
  # Use the official docker image.
  stage: Build
  script:
    - docker build -t  webtweet:v1.0.0  ./app/
    - docker save webtweet:v1.0.0  > webtweet.tar
  artifacts:
    paths:
      - webtweet.tar    


#############################################################
######      PHASE DE TEST ET ACCEPTATION     ################
#############################################################
Phase Test acceptance:
  # Official docker image.
  stage: Test acceptance
  script:
    - docker load < webtweet.tar
    - docker run -d -p 80:80 -e PORT=80 --name webtweet_test webtweet:v1.0.0
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker" | grep  "Linux Tweet App!"
    - curl "http://docker" | grep  "You've successfully deployed the Linux tweet app! Why not let the world know?"


#############################################################
###### PHASE DE RELEASE DE L'IMAGE GITLAB REGISTRY ##########
#############################################################
Phase Release image:
  stage: Release image
  script:
    - docker load < webtweet.tar
    - docker tag webtweet "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
#    - docker tag webtweet "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
#    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"

