default:
  tags:
    - ib-bdx
    - staging
    - docker

variables:
  PREPROD_IP: 192.168.99.20

image: docker:latest
services:
  - name: docker:dind
    alias: docker

stages:
  - test_ssh

Test cmd over ssh:
  stage: test_ssh
  tags:
    - ib-bdx
    - staging
    - shell
  script:
    - ssh vagrant@$PREPROD_IP 'echo Welcome on $HOSTNAME'
    - scp /tmp/webtweet_latest.tar vagrant@$PREPROD_IP:/tmp/
    - ssh vagrant@$PREPROD_IP 'docker load < /tmp/webtweet_latest.tar'
    - ssh vagrant@$PREPROD_IP 'docker run --rm -d -p 8080:80 --name webtweet webtweet:latest'
