#############################################################
###### VARIABLES & MISE EN OEUVRE DOCKER IN DOCKER ##########
#############################################################
default:
  tags:
    - ib-bdx
variables:
    IMAGE_NAME: registry.gitlab.com/rmaziere/fil-rouge-devops
    SNYK_TOKEN: "95633847-26f4-46d5-8be0-235d04d90fce"
    DOCKERHUB_ID: registry.gitlab.com/rmaziere
    SHORT_IMAGE_NAME: fil-rouge-devops
    IMAGE_TAG: main
    SPECIFIC_RUNNER_TAG: ib-bdx


image: docker:latest
services:
  - name: docker:dind
    alias: docker

#############################################################
######     DIFFERENTES ETAPES DE LA CI-CD   #################
#############################################################
stages:
  - Build
  - Test acceptance
  - Release image
  - Scan Securite
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging  
  - Deploy pre-prod
  - Test pre-prod
  - Deploy prod
  - Test prod


#############################################################
######       FONCTION TEST DE TEMPLATE    ###################
#############################################################
.test_template: &test
  image: ${IMAGE_NAME}:${IMAGE_TAG}
  only:
    - main
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep "Linux Tweet App!"  



#############################################################
######           PHASE DE BUILD         #####################
#############################################################
Phase Docker build:
  # Use the official docker image.
  stage: Build
  tags:
    - $SPECIFIC_RUNNER_TAG
  script:
    - docker build -t  webtweet:v1.0.0   .
    - docker tag webtweet:v1.0.0  webtweet:latest
    - docker save webtweet:v1.0.0  > webtweet.tar
  artifacts:
    paths:
      - webtweet.tar    


#############################################################
######      PHASE DE TEST ET ACCEPTATION     ################
#############################################################
Phase Test acceptance:
  # Official docker image.
  stage: Test acceptance
  script:
    - docker load < webtweet.tar
    - docker rm webtweet_test
    - docker run -d -p 80:80 -e PORT=80 --name webtweet_test webtweet:v1.0.0
    - sleep 5
    - apk --no-cache add curl
#    - curl "http://docker" | grep  "Linux Tweet App!"
#    - curl "http://docker" | grep  "You've successfully deployed the Linux tweet app! Why not let the world know?"
    - curl "http://127.0.0.1/" | grep  "You've successfully deployed the Linux tweet app! Why not let the world know?"


#############################################################
###### PHASE DE RELEASE DE L'IMAGE GITLAB REGISTRY ##########
#############################################################
Phase Release image:
  stage: Release image
  script:
    - docker load < webtweet.tar
    - docker tag webtweet:v1.0.0 "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
#    - docker tag webtweet "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
#    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"



#############################################################
######    PHASE DE SCAN DE SECURITE AVEC SNYK ###############
#############################################################
Phase Scan securite:
  stage: Scan Securite
  script:
    - docker run --rm -e SNYK_TOKEN=$SNYK_TOKEN 
        -v /var/run/docker.sock:/var/run/docker.sock 
        -v $(pwd):/app snyk/snyk:docker 
        snyk test --docker $DOCKERHUB_ID/$SHORT_IMAGE_NAME:$IMAGE_TAG --json || true;



#############################################################
######   PHASE REVUE DEPLOIEMENT AVEC STOP REVIEW  ##########
#############################################################
Phase deploy review:
  stage: Deploy review
#  tags:
#    - $SPECIFIC_RUNNER_TAG

  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://ibdevops4amn-$CI_COMMIT_REF_NAME.herokuapp.com
    on_stop: Phase Stop review # see de label Phase Stop review BELOW
  only:
    - merge_requests
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create ibdevops4amn-$CI_COMMIT_REF_NAME  || echo "project already exist"
    - heroku container:push --app ibdevops4amn-$CI_COMMIT_REF_NAME web
    - heroku container:release --app ibdevops4amn-$CI_COMMIT_REF_NAME web





#############################################################
######  PHASE DE STOP DE REVUE AVANT CONTINUATION ###########
#############################################################
Phase Stop review:
  stage: Stop review
#  tags:
#    - $SPECIFIC_RUNNER_TAG
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy --app ibdevops4amn-$CI_COMMIT_REF_NAME -c ibdevops4amn-$CI_COMMIT_REF_NAME



#############################################################
###### PHASE DEPLOIEMENT SUR ENVI DE STAGING HEROKU #########
#############################################################
Phase Deploy staging:
  stage: Deploy staging
#  tags:
#    - $SPECIFIC_RUNNER_TAG

  environment:
    name: staging
    url: https://ibdevops4amn-staging.herokuapp.com
  only:
    - main
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create ibdevops4amn-staging || echo "project already exist"
    - heroku container:push --app ibdevops4amn-staging web
    - heroku container:release --app ibdevops4amn-staging web


#############################################################
###### PHASE DEPLOIEMENT SUR ENVI DE PREPROD HEROKU #########
#############################################################
Phase Deploy pre-prod:
  stage: Deploy pre-prod
#  tags:
#    - $SPECIFIC_RUNNER_TAG

  environment:
    name: pre-prod
    url: https://ibdevops4amn-pre-prod.herokuapp.com
  only:
    - main
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create ibdevops4amn-pre-prod || echo "project already exist"
    - heroku container:push --app ibdevops4amn-pre-prod web
    - heroku container:release --app ibdevops4amn-pre-prod web


#############################################################
###### PHASE DEPLOIEMENT SUR ENVI DE PROD HEROKU    #########
#############################################################
Phase Deploy prod:
  stage: Deploy prod
#  tags:
#    - $SPECIFIC_RUNNER_TAG
  environment:
    name: prod
    url: https://ibdevops4amn-prod.herokuapp.com
  only:
    - main
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create ibdevops4amn-prod || echo "project already exist"
    - heroku container:push --app ibdevops4amn-prod web
    - heroku container:release --app ibdevops4amn-prod web


#############################################################
######  3 PHASES TESTS POUR STAING PREPROD ET PROD ##########
#############################################################

Phase de Test staging:
  <<: *test
  stage: Test staging
  variables:
    DOMAIN: ibdevops4amn-staging.herokuapp.com

Phase de Test pre-prod:
  <<: *test
  stage: Test pre-prod
  variables:
    DOMAIN: ibdevops4amn-pre-prod.herokuapp.com

Phase de Test prod:
  <<: *test
  stage: Test prod
  variables:
    DOMAIN: ibdevops4amn-prod.herokuapp.com

